services:
  app:
    build: .
    volumes:
      - .:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`myapp.localhost`)"
      - "traefik.http.routers.myapp.entrypoints=websecure"
      - "traefik.http.routers.myapp.tls=true"
      - "traefik.http.routers.myapp.tls.certresolver=default"
    networks:
      - traefik
networks:
  traefik:
    external: true